version: 2.1
jobs:
 Publish-to-Pages:
   docker:
     - image: cimg/node:18
   environment:
     CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
     CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN

   steps:
     - checkout
     # Run your project's build step
     - run: npm install && npm run build
     # Publish with wrangler
     - run: npx wrangler pages publish build --project-name=reactdemo # Replace dist with the name of your build folder and input your project name

workflows:
 Publish-to-Pages-workflow:
   jobs:
     - Publish-to-Pages
